name: Run Tests
description: Run unit test for the current application
inputs:
  tool4d_download_url:
    required: false
  type: string
    tool4d_executable_path: 
  required: true
    type: string
  startup_method: 
    required: true
  type: string  
    project_path: 
  required: true
    type: string  

runs:
  using: "composite"
  steps:
    - name: check platform windows
      run: |
        ${TOOL4D_EXECUTABLE_PATH} ${PROJECT_PATH} --startup-method=${PROJECT_STARTUP_METHOD} --dataless
        UTestResult=`cat application/UTestResult.txt`
        value=`head -n 1 application/UTestResult.txt`
        rm application/UTestResult.txt
        if [ "$value" = "Unit tests failed" ]; then
          exit 1
        fi
      shell: bash
      env:
        TOOL4D_EXECUTABLE_PATH: ${{ inputs.tool4d_executable_path }}
        TOOL4D_DOWNLOAD_URL: ${{ inputs.tool4d_download_url }}
        PROJECT_STARTUP_METHOD: ${{ inputs.startup_method }}
        PROJECT_PATH: ${{ inputs.project_path }}
