name: Build for macOS

on:      
  push:
    branches:
      - main
      
  workflow_call: 
    inputs:
      version: 
        required: true
        type: string
      mode: 
        required: true
        type: string
      upload_url:
        required: true
        type: string

env: 

  DEVELOPER_ID: "Developer ID Application: keisuke miyako (Y69CWUC25B)"
  BUILD_DIR: build        
  PRODUCT_NAME: application   
  NOTARYTOOL_KEYCHAIN_PROFILE: notarytool
  BUILD_PROJECT_PATH: application/Project/application.4DProject
  BUILD_SETTINGS_PATH: application/Settings/buildApp.4DSettings
  
jobs:
          
  build:
    uses: miyako/4D/.github/workflows/build-macos.yml@v1
    with:
    # event_name of workflow_call is workflow_dispatch
      development: ${{ github.event_name == 'workflow_dispatch' && inputs.version != null }}
      version: ${{ inputs.version }}
      mode: ${{ inputs.mode }}
      upload_url: ${{ inputs.upload_url }}
      developer_id: ${{ env.DEVELOPER_ID }}
      build_dir: ${{ env.BUILD_DIR }}
      product_name: ${{ env.PRODUCT_NAME }}
      notarytool_keychain_profile: ${{ env.NOTARYTOOL_KEYCHAIN_PROFILE }}
      build_project_path: ${{ env.BUILD_PROJECT_PATH }}
      build_settings_path: ${{ env.BUILD_SETTINGS_PATH }}
