name: 🎯Build for macOS

on:      
  push:
    branches:
      - main
      
  workflow_call: 
    inputs:
      version: 
        required: true
        type: string
      mode: 
        required: true
        type: string
      upload_url:
        required: true
        type: string
      developer_id:
        required: true
        type: string
      build_dir:
        required: true
        type: string
      product_name:
        required: true
        type: string
      notarytool_keychain_profile:
        required: true
        type: string
      build_project_path:
        required: true
        type: string
      build_settings_path:
        required: true
        type: string  
      
jobs:

  get-tool:
    uses: miyako/4D/.github/workflows/get-tool.yml@v1
    with:
      platform: macos
      labels: "[\"macos\", \"self-hosted\"]"
      branch: 20.x
      version: 20.2
      build: 100959
          
  build:
    needs: get-tool
    uses: miyako/4D/.github/workflows/build-macos.yml@v1
    with:
      development: ${{ github.event_name == 'workflow_dispatch' && inputs.version != null }}
      
      version: ${{ inputs.version }}
      mode: ${{ inputs.mode }}
      upload_url: ${{ inputs.upload_url }}
      
      developer_id: ${{ inputs.developer_id }}
      build_dir: ${{ inputs.build_dir }}
      product_name: ${{ inputs.product_name }}
      notarytool_keychain_profile: ${{ inputs.notarytool_keychain_profile }}
      build_project_path: ${{ inputs.build_project_path }}
      build_settings_path: ${{ inputs.build_settings_path }}
