name: Build

on:
  push:
    branches:
      - main
      
  workflow_call: 
    inputs:
      version: 
        required: true
        type: string
      mode: 
        required: true
        type: string

env: 
  DEVELOPER_ID: "Developer ID Application: keisuke miyako (Y69CWUC25B)"
  BUILD_DIR: build        
        
jobs:
          
  compile:
    runs-on: [self-hosted]
    
    steps:
      - name: checkout compiler repo
        uses: actions/checkout@v4
        with:
          repository: miyako/4d-class-compiler
          path: compiler
      - name: compile project
        run: |
          tool4d.app/Contents/MacOS/tool4d ./compiler/Project/compiler.4DProject --startup-method=localbuild --user-param=$PWD/application/Settings/buildApp.4DSettings,$PWD/application/Project/application.4DProject --dataless
      - name: prepare for distribution
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.version != null }}
        run: |
          PRODUCT_PATH=$PWD/$BUILD_DIR/application.app
          DMG_PATH=$PWD/$BUILD_DIR/application.dmg
          codesign --verbose --deep --timestamp --force --sign "$DEVELOPER_ID" --options=runtime $PRODUCT_PATH 
          hdiutil create -format UDBZ -plist -srcfolder $PRODUCT_PATH $DMG_PATH
          xcrun notarytool submit --keychain-profile "notarytool" $DMG_PATH --wait
          xcrun stapler staple $DMG_PATH
              
      - name: upload product
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./${BUILD_DIR}/application.dmg
          asset_name: application.dmg
          asset_content_type: application/octet-stream
