name: Build

on:
  push:
    branches:
      - main
    paths:
      - package.json
      
jobs:

  test:
    runs-on: [self-hosted]
  
    steps:
      - uses: actions/checkout@v4
      - name: download latest tool4d
        run: |        
          curl https://resources-download.4d.com/release/20%20Rx/20%20R3/100050/mac/tool4d_v20R3_mac_arm.tar.xz -o tool4d.tar.xz -sL
          tar xvJf tool4d.tar.xz
      - name: run unit tests
        run: |
          tool4d.app/Contents/MacOS/tool4d ./application/Project/application.4DProject --startup-method=test --dataless
          UTestResult=`cat application/UTestResult.txt`
          value=`head -n 1 application/UTestResult.txt`
          rm application/UTestResult.txt
          if [ "$value" = "Unit tests failed" ]
          then
            exit 1
          fi
          
  compile:
    needs: test
    runs-on: [self-hosted]

    steps:
      - name: checkout compiler repo
        uses: actions/checkout@v4
        with:
          repository: miyako/4d-class-compiler
          path: compiler
      - name: compile project
        run: |
          tool4d.app/Contents/MacOS/tool4d ./compiler/Project/compiler.4DProject --startup-method=localbuild --user-param=$PWD/application/Settings/buildApp.4DSettings,$PWD/application/Project/application.4DProject --dataless
