name: Bump

on:
  workflow_call: 
    inputs:
      mode: 
        required: true
        type: string
    outputs:
       version:
         value: ${{ jobs.bump.outputs.version }}
       mode:
         value: ${{ inputs.mode }}
        
jobs:

    bump:
      runs-on: ubuntu-latest
      outputs:
        version: ${{ steps.version.outputs.version }}
        
      steps:
        - uses: actions/checkout@v4
        - name: git config 
          run: |
            git config --local user.name "GitHub Action"
            git config --local user.email "action@github.com"          
        - name: major
          if: ${{ inputs.mode == 'major' }} 
          run: |
            npm version major
        - name: minor
          if: ${{ inputs.mode == 'minor' }} 
          run: |
            npm version minor
        - name: patch
          if: ${{ inputs.mode == 'patch' }} 
          run: |
            npm version patch
        - name: git push
          run: |
            git push origin
        - id: version
          run: |
            VERSION=`cat package.json | jq -r '.version'`
            echo "version=$VERSION" >> $GITHUB_OUTPUT
