name: CICD

on:
  push:
    branches: [ "main" ]

jobs:

  compile:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3
      - name: "download latest tool4d"
        run: |        
          curl https://resources-download.4d.com/release/20.x/20.2/latest/mac/tool4d_v20.2_mac_arm.tar.xz -o tool4d.tar.xz -sL
          tar xvJf tool4d.tar.xz
      - name: checkout compiler repo
        uses: actions/checkout@v4
        with:
          repository: miyako/4d-class-compiler
          path: compiler
      - name: compile project
        run: |
          tool4d.app/Contents/MacOS/tool4d --startup-method=build --user-param=./application/buildApp.4DSettings,./application/Project/application.4DProject  --dataless
          
