name: Publish

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: semantic versioning
        options: 
        - patch
        - minor 
        - major
        required: true
