name: Publish

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: semantic versioning
        options: 
        - patch
        - minor 
        - major
        required: true
        
jobs:

    hello:
        runs-on: ubuntu-latest

        steps:
          - name: print mode
            run: |
              echo "Mode: ${{ github.event.inputs.mode }}"
              if [${{ github.event.inputs.version }} == "major"]
              then
                yarn version major
              elif [${{ github.event.inputs.version }} == "minor"]
                yarn version minor
              elif [${{ github.event.inputs.version }} == "patch"]
                yarn version patch
              fi
              echo yarn version --non-interactive | grep "Current version:" | awk '{ print $4 }
