name: Publish

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: semantic versioning
        options: 
        - patch
        - minor 
        - major
        required: true
        
jobs:

    hello:
        runs-on: macos-latest

        steps:
          - uses: actions/checkout@v3
          - name: major
            if: ${{ github.event.inputs.mode == 'major' }} 
            run: |
              yarn version --major
          - name: minor
            if: ${{ github.event.inputs.mode == 'minor' }} 
            run: |
              yarn version --minor              
          - name: patch
            if: ${{ github.event.inputs.mode == 'patch' }} 
            run: |
              yarn version --minor    
          - name: print current version   
            run: |
              mode=${{ github.event.inputs.mode }}
              version=`cat package.json | jq -r '.version'`
              echo "version:$version"
              echo "mode:$mode"
