name: Publish

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: semantic versioning
        options: 
        - patch
        - minor 
        - major
        required: true
        
jobs:

    bump:
        runs-on: ubuntu-latest # fail on ubuntu-latest
        
        steps:
          - uses: actions/checkout@v4
          - name: git config 
            run: |
              git config --local user.name "GitHub Action"
              git config --local user.email "action@github.com"          
          - name: major
            if: ${{ github.event.inputs.mode == 'major' }} 
            run: |
              # yarn version --major
              npm version major
          - name: minor
            if: ${{ github.event.inputs.mode == 'minor' }} 
            run: |
              # yarn version --minor
              npm version minor
          - name: patch
            if: ${{ github.event.inputs.mode == 'patch' }} 
            run: |
              # yarn version --patch
              npm version patch
          - name: git config 
            run: |
              version=`cat package.json | jq -r '.version'`
              # git commit -m "bump version to $version" -a
              git push
