name: 🎉Publish

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: semantic versioning
        options: 
        - patch
        - minor 
        - major
        required: true
      test:
        type: boolean
        description: run tests
        default: true

jobs:

  bump:
    uses: miyako/4D/.github/workflows/bump.yml@v1
    with:
      mode: ${{ github.event.inputs.mode }} 

  release:
    needs: bump
    uses: miyako/4D/.github/workflows/create-release.yml@v1
    with:
      version: ${{ needs.bump.outputs.version }}
      mode: ${{ needs.bump.outputs.mode }} 
      
  build:
    needs: 
    - bump
    - release
    uses: ./.github/workflows/build-macos.yml
    with:
      version: ${{ needs.bump.outputs.version }}
      mode: ${{ needs.bump.outputs.mode }}
      upload_url: ${{ needs.release.outputs.upload_url }}
