name: Publish

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: semantic versioning
        options: 
        - patch
        - minor 
        - major
        required: true
      test:
        type: boolean
        description: run tests
        default: true

jobs:

  bump:
    uses: ./.github/workflows/bump.yml
    with:
      mode: ${{ github.event.inputs.mode }} 

  release:
    needs: bump
    uses: ./.github/workflows/create-release.yml
    with:
      version: ${{ needs.bump.outputs.version }}
      mode: ${{ needs.bump.outputs.mode }} 

  # test:
  #   if: ${{ github.event.inputs.test }}
  #   uses: ./.github/workflows/test.yml
  #   with:
  #     windows: true
  #     macos: true
      
  build:
    needs: 
    - bump
    - release
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.bump.outputs.version }}
      mode: ${{ needs.bump.outputs.mode }}
      upload_url: ${{ needs.release.outputs.upload_url }}
