name: 🎉Publish

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: semantic versioning
        options: 
        - patch
        - minor 
        - major
        required: true
      test:
        type: boolean
        description: run tests
        default: true

env: 

  DEVELOPER_ID: "Developer ID Application: keisuke miyako (Y69CWUC25B)"
  BUILD_DIR: build        
  PRODUCT_NAME: application   
  NOTARYTOOL_KEYCHAIN_PROFILE: notarytool
  BUILD_PROJECT_PATH: application/Project/application.4DProject
  BUILD_SETTINGS_PATH: application/Settings/buildApp.4DSettings
  
jobs:

  bump:
    uses: miyako/4D/.github/workflows/bump.yml@v1
    with:
      mode: ${{ github.event.inputs.mode }} 

  release:
    needs: bump
    uses: miyako/4D/.github/workflows/create-release.yml@v1
    with:
      version: ${{ needs.bump.outputs.version }}
      mode: ${{ needs.bump.outputs.mode }} 
      
  build:
    needs: 
    - bump
    - release
    uses: ./.github/workflows/build-macos.yml
    with:
      version: ${{ needs.bump.outputs.version }}
      mode: ${{ needs.bump.outputs.mode }}
      upload_url: ${{ needs.release.outputs.upload_url }}
      
      developer_id: ${{ env.DEVELOPER_ID }}
      build_dir: ${{ env.BUILD_DIR }}
      product_name: ${{ env.PRODUCT_NAME }}
      notarytool_keychain_profile: ${{ env.NOTARYTOOL_KEYCHAIN_PROFILE }}
      build_project_path: ${{ env.BUILD_PROJECT_PATH }}
      build_settings_path: ${{ env.BUILD_SETTINGS_PATH }}
