name: 🎉Publish

on:     
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: semantic versioning
        options: 
        - patch
        - minor 
        - major
        required: true
      test:
        type: boolean
        description: run tests
        default: true
      developer_id: 
        type: string
        default: "Developer ID Application: keisuke miyako (Y69CWUC25B)"
      build_dir: 
        type: string
        default: build
      product_name: 
        type: string
        default: application
      notarytool_keychain_profile: 
        type: string
        default: notarytool
      build_project_path: 
        type: string
        default: application/Project/application.4DProject
      build_settings_path: 
        type: string
        default: application/Settings/buildApp.4DSettings
      test_startup_method: 
        type: string
        default: test
  
jobs:

  bump:
    uses: miyako/4D/.github/workflows/bump.yml@v1
    with:
      mode: ${{ github.event.inputs.mode }} 

  release:
    needs: bump
    uses: miyako/4D/.github/workflows/create-release.yml@v1
    with:
      version: ${{ needs.bump.outputs.version }}
      mode: ${{ needs.bump.outputs.mode }} 

  tool4d:
    needs: 
    - bump
    - release
    runs-on: [macos, self-hosted]
    steps:
    
      - name: checkout 
        uses: actions/checkout@v4
        
      - name: get tool4d
        id: get
        uses: miyako/4D/.github/actions/get-tool@v1
        with:
          platform: macos
          branch: 20.x
          version: 20.2
          build: 100959
          arch: arm
          
      # - name: run tests
      #   uses: ./.github/actions/run-tests
      #   with:
      #     tool4d_download_url: ${{ steps.get.outputs.tool4d_download_url }}
      #     tool4d_executable_path: ${{ steps.get.outputs.tool4d_executable_path }}
      #     startup_method: ${{ inputs.test_startup_method }}
      #     project_path: ${{ inputs.build_project_path }}  

      - name: build macos
        id: build
        uses: miyako/4D/.github/actions/build-macos@v1
        with:
          deployment: ${{ github.event_name == 'workflow_dispatch' && needs.bump.outputs.version != null }}
          version: ${{ needs.bump.outputs.version }}
          mode: ${{ needs.bump.outputs.mode }}
          upload_url: ${{ needs.release.outputs.upload_url }}
          developer_id: ${{ inputs.developer_id }}
          build_dir: ${{ inputs.build_dir }}
          product_name: ${{ inputs.product_name }}
          notarytool_keychain_profile: ${{ inputs.notarytool_keychain_profile }}
          build_project_path: ${{ inputs.build_project_path }}
          build_settings_path: ${{ inputs.build_settings_path }}

      - name: upload product
        if: ${{ steps.build.deployment }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.build.upload_url }}
          asset_path: ${{ steps.build.asset_path }}
          asset_name: ${{ steps.build.asset_name }}
          asset_content_type: application/octet-stream
            
