name: Publish

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: semantic versioning
        options: 
        - patch
        - minor 
        - major
        required: true
        
jobs:

    hello:
        runs-on: macos-latest

        steps:
          - uses: actions/checkout@v3
          - name: print mode
            run: |
              mode="${{ github.event.inputs.mode }}"
              echo "Mode: $mode"
              if   [$mode == "major"]
              then

              elif [$mode == "minor"]
              then

              else

              fi
              echo yarn version --non-interactive | grep "Current version:" | awk '{ print $4 }
