name: 🎉Publish

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: semantic versioning
        options: 
        - patch
        - minor 
        - major
        required: true
      test:
        type: boolean
        description: run tests
        default: true
      developer_id: 
        type: string
        default: "Developer ID Application: keisuke miyako (Y69CWUC25B)"
      build_dir: 
        type: string
        default: build
      product_name: 
        type: string
        default: application
      notarytool_keychain_profile: 
        type: string
        default: notarytool
      build_project_path: 
        type: string
        default: application/Project/application.4DProject
      build_settings_path: 
        type: string
        default: application/Settings/buildApp.4DSettings
  
jobs:

  bump:
    uses: miyako/4D/.github/workflows/bump.yml@v1
    with:
      mode: ${{ github.event.inputs.mode }} 

  release:
    needs: bump
    uses: miyako/4D/.github/workflows/create-release.yml@v1
    with:
      version: ${{ needs.bump.outputs.version }}
      mode: ${{ needs.bump.outputs.mode }} 
      
  build:
    needs: 
    - bump
    - release
    uses: ./.github/workflows/build-macos.yml
    with:
      version: ${{ needs.bump.outputs.version }}
      mode: ${{ needs.bump.outputs.mode }}
      upload_url: ${{ needs.release.outputs.upload_url }}
      # env is not available in this context
      developer_id: ${{ inputs.developer_id }}
      build_dir: ${{ inputs.build_dir }}
      product_name: ${{ inputs.product_name }}
      notarytool_keychain_profile: ${{ inputs.notarytool_keychain_profile }}
      build_project_path: ${{ inputs.build_project_path }}
      build_settings_path: ${{ inputs.build_settings_path }}
