name: Publish

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: semantic versioning
        options: 
        - patch
        - minor 
        - major
        required: true

jobs:

  bump:
    uses: ./.github/workflows/bump.yml
    with:
      mode: ${{ github.event.inputs.mode }} 

  create-release:
    needs: bump
    uses: ./.github/workflows/create-release.yml
    with:
      version: ${{ needs.bump.outputs.version }}
      mode: ${{ needs.bump.outputs.mode }} 
      
  build:
    needs: bump
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.bump.outputs.version }}
      mode: ${{ needs.bump.outputs.mode }}
