name: Publish

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: semantic versioning
        options: 
        - patch
        - minor 
        - major
        required: true
        
jobs:

    bump:
        runs-on: macos-latest # fail on ubuntu-latest
        
        steps:
          - uses: actions/checkout@v4
          - name: major
            if: ${{ github.event.inputs.mode == 'major' }} 
            run: |
              yarn version --major
          - name: minor
            if: ${{ github.event.inputs.mode == 'minor' }} 
            run: |
              yarn version --minor              
          - name: patch
            if: ${{ github.event.inputs.mode == 'patch' }} 
            run: |
              yarn version --minor
          - name: commit 
            run: |
              mode=${{ github.event.inputs.mode }}
              version=`cat package.json | jq -r '.version'`
              git config --local user.name "GitHub Action"
              git config --local user.email "action@github.com"
              git commit -m "bump version to $version" -a
              git push
  
