name: Publish

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: semantic versioning
        options: 
        - patch
        - minor 
        - major
        required: true

jobs:

  publish:
    runs-on: [self-hosted]

    steps:
    - name: bump semantic versioning
    - run: |
        echo "::mode::${{ github.event.inputs.version }}"
