name: Test

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      labels: 
        required: true
        type: string
      branch: 
        required: true
        type: string
      version: 
        required: true
        type: string
      build: 
        required: true
        type: string
      windows:
        required: true
        type: boolean
      macos:
        required: true
        type: boolean  

env: 
  platform: ${{ (startsWith(inputs.platform, 'windows') && (inputs.windows == true)) || (startsWith(inputs.platform, 'macos') && (inputs.macos == true)) }}

jobs:     

  setup:
    steps:
    - name: get tool4d 
      id:get
      if: ${{ env.platform }}
      uses: miyako/4D/.github/workflows/get-tool.yml@v1
      with:
      platform: ${{ inputs.platform }}
      labels: ${{ inputs.labels }} 
      branch: ${{ inputs.branch }}
      version: ${{ inputs.version }}
      build: ${{ inputs.build }}
      
    - name: checkout repository
      if: ${{ env.platform }}
      uses: actions/checkout@v4

  tests:   
    needs: setup

# end of generic code
# customise the fail condition here
# in the example below, we test the result log file

    - name: unit tests
      if: ${{ env.platform }}
      run: |
        ${TOOL4D_EXECUTABLE_PATH} ${PROJECT_PATH} --startup-method=${PROJECT_STARTUP_METHOD} --dataless
        UTestResult=`cat application/UTestResult.txt`
        value=`head -n 1 application/UTestResult.txt`
        rm application/UTestResult.txt
        if [ "$value" = "Unit tests failed" ]
        then
          exit 1
        fi
      shell: bash
      env:
        TOOL4D_EXECUTABLE_PATH: ${{ jobs.setup.steps.get.tool4d_executable_path }}
        CURL_DOWNLOAD_URL: ${{ jobs.setup.steps.get.outputs.tool4d_download_url }}
