name: Test

on:
  workflow_call:
 
jobs:     

  get:
    strategy:
      matrix:
        TOOL4D_PLATFORM: ["windows-latest", "macos-latest"]
        TOOL4D_BRANCH: [20.x]
        TOOL4D_VERSION: [20.2]
        TOOL4D_BUILD: [latest] 
    runs-on: ${{ matrix.TOOL4D_PLATFORM }}
    steps:
      - name: get tool4d
        id: get
        uses: miyako/4D/.github/actions/get-tool@v1
        with:
          platform: macos
          branch: 20.x
          version: 20.2
          build: latest
      - name: run tests
        uses: ./.github/actions/run-tests@v1
        with:
          tool4d_download_url: steps.get.outputs.tool4d_download_url
          tool4d_executable_path: steps.get.outputs.tool4d_download_url
          startup_method: test
          project_path: ./application/Project/application.4DProject          
