name: Test for macOS

on:      
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
    
  setup:
    uses: miyako/4D/.github/workflows/get-tool.yml@v1
    with:
      platform: macos
      labels: "[\"macos-latest\"]"
      branch: 20.x
      version: 20.2
      build: latest

  test:
    needs: setup
    runs-on: [macos-latest]   
    steps:
    - name: unit tests
      run: |
        ${TOOL4D_EXECUTABLE_PATH} ${PROJECT_PATH} --startup-method=${PROJECT_STARTUP_METHOD} --dataless
        UTestResult=`cat application/UTestResult.txt`
        value=`head -n 1 application/UTestResult.txt`
        rm application/UTestResult.txt
        if [ "$value" = "Unit tests failed" ]
        then
          exit 1
        fi
      shell: bash
      env:
        TOOL4D_EXECUTABLE_PATH: ${{ needs.setup.outputs.tool4d_executable_path }}
        CURL_DOWNLOAD_URL: ${{ needs.setup.outputs.tool4d_download_url }}
    
