name: Test

on:
  push:
    branches:
      - main
      
  workflow_dispatch: 
   inputs:
      windows:
        type: boolean
        description: windows-latest
        default: true
      macos:
        type: boolean
        description: macos-latest
        default: true

  workflow_call:
    inputs:
      windows:
        required: true
        type: boolean
      macos:
        required: true
        type: boolean
             
jobs:

  test:
    strategy:
      matrix:
        TOOL4D_PLATFORM: ["windows-latest", "macos-latest"]
        TOOL4D_BRANCH: [20.x]
        TOOL4D_VERSION: [20.2]
        TOOL4D_BUILD: [latest] 
      # env is unavailable in a strategy
    uses: miyako/4D/.github/workflows/get-tool.yml@v1
    with:
      platform: ${{ matrix.TOOL4D_PLATFORM }}
      labels: ${{ toJSON(matrix.TOOL4D_PLATFORM) }} # must be JSON
      branch: ${{ matrix.TOOL4D_BRANCH }}
      version: ${{ matrix.TOOL4D_VERSION }}
      build: ${{ matrix.TOOL4D_BUILD }}
      onready: ./github/workflows/test_1.yml
