name: Test

on:
  push:
    branches:
      - main
      
  workflow_dispatch: 
   inputs:
      windows:
        type: boolean
        description: windows-latest
        default: true
      macos:
        type: boolean
        description: macos-latest
        default: true

  workflow_call:
    inputs:
      windows:
        required: true
        type: boolean
      macos:
        required: true
        type: boolean
             
jobs:

  get:
    strategy:
      matrix:
        TOOL4D_PLATFORM: [windows-latest, macos-latest]
        TOOL4D_BRANCH: [20.x, 20.x]
        TOOL4D_VERSION: [20.2, 20.2]
        TOOL4D_BUILD: [latest, latest] 
      # env is unavailable in a strategy
    uses: miyako/4D/.github/workflows/get-tool.yml@v1
    with:
      platform: ${{ toJSON(matrix.TOOL4D_PLATFORM) }}
      labels: ${{ matrix.TOOL4D_PLATFORM }}
      branch: ${{ matrix.TOOL4D_BRANCH }}
      version: ${{ matrix.TOOL4D_VERSION }}
      build: ${{ matrix.TOOL4D_BUILD }}
    
  checkout:
    needs: get
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}     
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        
# end of generic code
# customise the fail condition here
# in the example below, we test the result log file
   
  test:
    needs: checkout
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}     
    steps:
    - name: unit tests
      run: |
        ${TOOL4D_EXECUTABLE_PATH} ${PROJECT_PATH} --startup-method=${PROJECT_STARTUP_METHOD} --dataless
        UTestResult=`cat application/UTestResult.txt`
        value=`head -n 1 application/UTestResult.txt`
        rm application/UTestResult.txt
        if [ "$value" = "Unit tests failed" ]
        then
          exit 1
        fi
      shell: bash
      env:
        TOOL4D_EXECUTABLE_PATH: ${{ steps.get.outputs.tool4d_executable_path }}
        CURL_DOWNLOAD_URL: ${{ steps.get.outputs.tool4d_download_url }}
