name: 🧪Test Get Tool

on:
  workflow_dispatch: 

jobs:

  test:
    # uses: ./.github/workflows/get-tool.yml
    uses: miyako/4D/.github/workflows/get-tool.yml@v1
    with:
      platform: macos
      labels: "[\"macos\", \"self-hosted\"]"
      branch: 20.x
      version: 20.2
      build: 100959
